### ISSUE TITLE
Large Buttons

### ISSUE THREAD

**Issue by rafecolton** [timhuisman/css-social-media-buttons#12]
Hello,

Would it be possible to add a `.large` class that makes the buttons larger?  I was able to accomplish this artificially using the following css:
```css
.csmb.large, .csmb-flat.large {
  background-image: url("../images/icon-sprite-x2.png");
  height: 56px;
  width: 56px;
  background-size: auto !important;
}
```

However, as you might imagine, this makes the images look pixelated on retina devices.

Thank you for a wonderful product!  This is the best CSS sprite and css I have found so far :smile:
